<?php
/**
 * Archive template for the Locations CPT
 */

// Do not edit this file directly, follow this 'require once'. 
 require_once get_stylesheet_directory(  ) . '/inc/site/cpt/templates/archive-locations.php';