<?php
/**
 * The footer for our theme
 *
 * Displays all of the <footer> section
 *
 * @package Understrap
 */

// Do not edit this file directly, follow this 'require once'.
require_once get_stylesheet_directory(  ) . '/inc/site/template-parts/footer.php';
