<?php
/**
 * The header for our theme
 *
 * Displays all of the <head> section and everything up till <div id="content">
 *
 * @package Understrap
 */

// Do not edit this file directly, follow this 'require once'.
require_once get_stylesheet_directory(  ) . '/inc/site/template-parts/header.php';
