<?php
/**
 * Displays a single Location instance.

 */

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;

// Do not edit this file directly, follow this 'require once'. 
require_once get_stylesheet_directory(  ) . '/inc/site/cpt/templates/single-locations.php';